[book]
title = "NixOS Role-Based Configuration"
authors = ["NixOS User"]
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/yourusername/nixos-config"
